# Streamlit Cloud Secrets Template
# Copy this content to your Streamlit Cloud app secrets section
# DO NOT commit this file with real values to git

# OpenAI API Key
OPENAI_API_KEY = "your-openai-api-key-here"

# Google Sheet ID (the long string in your Google Sheets URL)
GOOGLE_SHEET_ID = "your-google-sheet-id-here"

# Google Service Account Credentials
[google_credentials]
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nyour-private-key-here\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account-email@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account-email%40your-project.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
